name: Release Windows

on:
  push:
    tags:
      - 'v*.*.*'
      
permissions:
  contents: write  # Ensure the token has write access to contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o ./tmp/app.exe .

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./tmp/app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}